### ISSUE TITLE
What does it mean to add a label set to another label set?

### ISSUE THREAD

**Issue by lawnsea** [w3c/webappsec-cowl#10]
The third step of the definition of [`and((Label or DOMString) other)` in 3.1.2](http://w3c.github.io/webappsec-cowl/#dom-label-and-label-or-domstring-other) says

> Return a new Label, in normal form, which is equivalent to adding O’s label set to the label set of the Label on which the method was invoked.

What does it mean to add one label set to another? It seems like this should be stated explicitly in terms of disjunction sets.

**Comment by deian** [comment]
Thanks1 Hope that clears it up!

**Comment by lawnsea** [comment]
:+1:
