### ISSUE TITLE
Sec-COWL request header possibly incompatible with RFC 2616

### ISSUE THREAD

**Issue by lawnsea** [w3c/webappsec-cowl#18]
Section 3.5.1 says that user agents can send additional `Sec-COWL` headers with labeled data metadata:

> The user agent MAY send another header with this field name whose value is labeled data metadata (e.g., when sending labeled objects with XMLHttpRequest).

Unfortunately, this seems to be in violation of RFC 2616. See [Section 4.2](http://tools.ietf.org/html/rfc2616#section-4.2). The relevant text follows (emphasis mine):

> Multiple message-header fields with the same field-name MAY be
>    present in a message if and only if the entire field-value for that
>    header field is defined as a comma-separated list [i.e., #(values)].
>    **It MUST be possible to combine the multiple header fields into one
>    "field-name: field-value" pair, without changing the semantics of the
>    message, by appending each subsequent field-value to the first, each
>    separated by a comma.**

It doesn't seem legal to do this combination into a comma-delimited list with the current ABNF.

**Comment by deian** [comment]
Thanks for catching this! In a pervious version I had allowed both context and data metadata in a single header. I'll fix the ABNF to allow this and for combining headers.

**Comment by lawnsea** [comment]
Great!
