### ISSUE TITLE
How should a server interpret multiple Sec-COWL headers?

### ISSUE THREAD

**Issue by lawnsea** [w3c/webappsec-cowl#19]
How should a server understand a request containing the following headers?

```
Sec-COWL: ctx-confidentiality [ ['https://a.com'] ];
          ctx-integrity [ [] ];
          ctx-privilege [ ['https://b.com'] ];
Sec-COWL: ctx-confidentiality [ ['https://b.com'] ];
          ctx-integrity [ [] ];
          ctx-privilege [ ['https://a.com'] ];
```

[Section 4.9](http://w3c.github.io/webappsec-cowl/#process-response) states how to interpret the following headers in a response (i.e., ignore the second header):

```
Sec-COWL: ctx-privilege [ ['self', 'cowl://user1'] ];
Sec-COWL: ctx-privilege [ ['self', 'cowl://user2'] ];
```

I think COWL should similarly state how to handle multiple `Sec-COWL` headers in a request.

**Comment by deian** [comment]
A conforming UA should never send multiple `Sec-COWL` headers. (This is because we have sole control over the header and it unsafe for it to be set JS.) I should add text to clarify this. Does this make sense to you?

**Comment by lawnsea** [comment]
Yes, that makes sense. It might be good to also say what the server should do if it receives multiple request headers (use the first one only, e.g.).

**Comment by deian** [comment]
Closing bug. @lawnsea let me know if you don't think that the text addresses this sufficiently.
