### ISSUE TITLE
HTTP Header Field sections

### ISSUE THREAD

**Issue by dret** [w3c/webappsec-cowl#24]
this is probably just nitpicking, but http://www.w3.org/TR/COWL/#header talks about "HTTP Header Field_s_", while it seems that the spec is only defining one field, and using it differently in requests and responses. afaict it's ok to do this, but it still only is one header field, and not two.

**Comment by dret** [comment]
why not just say: "The Sec-COWL HTTP header field is used to convey label metadata."

**Comment by deian** [comment]
You're right, thanks! I'll fix this this week.
