### ISSUE TITLE
Should a LabeledObject's protected object be cloned as well?

### ISSUE THREAD

**Issue by lawnsea** [w3c/webappsec-cowl#29]
[Section 4.7, step 4](https://github.com/w3c/webappsec-cowl/blob/master/index.src.html#L2599-L2603) says:

> If input is a LabeledObject object, let output be a newly constructed LabeledObject object with the same internal protected object, confidentiality label, and integrity label as that of input.

If a `LabeledObject` is transferred to another JS context (via PostMessage, e.g.) then the receiving context cannot get the same object. Should this step instead say something like this?

> let `output` be a newly constructed `LabeledObject` object with an internal protected object that is a structured clone of the protected object of the `input` `LabeledObject`

**Comment by deian** [comment]
Glad you brought this up! I didn't add the additional structured clone because the protected object is already a structured clone of something else, but I think adding is both safer (to future changes) and more consistent.

**Comment by lawnsea** [comment]
:+1:
