### ISSUE TITLE
Should top-level pages be able to navigate arbitrarily?

### ISSUE THREAD

**Issue by deian** [w3c/webappsec-cowl#44]
Following up on #34. Current version of spec has the invariant of ensuring that top-level contexts never get _stuck_. Getting _stuck_ means not being able to navigate at all. It, however, doesn't mean that you can navigate arbitrarily. Do we want to be more permissive and define _stuck_ as being able to navigate arbitrarily?

**Comment by deian** [comment]
After some discussion with +@NAndreasson (who is working on the FF implementation), it seems like we should only allow iframes to be confined. Rather than get _stuck_ we should maybe rewrite the text to highlight the fact that top-level contexts can't get tainted/confined.

**Comment by jonathanKingston** [comment]
This would tie into the document.domain ticket that is also happening
right? This has the ability to taint.

**Comment by deian** [comment]
@jonathanKingston can you clarify?
