### ISSUE TITLE
Specify same-origin IPC vs. shared memory edgecase 

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#47]
An interesting case which can be further specified is how we handle the same-origin case, where one site, such as `a.com` includes an iFrame to the same-origin (e.g `a.com/other.html`) which has enabled COWL (without reading sensitive information). Technically they both have the same privilege (a.com) and   have an empty confidentiality label. Should we revoke shared memory access and then only use message passing, or should it be an implementation choice?
# Example
## a.com

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>A.com</title>
</head>
<body>
<h1>A.com</h1>
<iframe id="a-iframe" src="http://a.com/other.html"></iframe>
<script>
  var aIFrame = document.getElementById('a-iframe');
  aIFrame.onload = function() {
    console.log('Accessing content from frame');
    console.log('Test', aIFrame.contentWindow.test);
  };
</script>
</body>
</html>
```
## a.com/other.html

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Other a.com</title>
</head>
<body>
<h1>Other a.com</h1>
<script>
  COWL.enable();
  window.test = "Test";
</script>
</body>
</html>
```

**Comment by deian** [comment]
I think that there are arguments to be made for both design choices and something we should discuss on the webappsec list. My intuition is to lean on the side of security and just say that once you enable COWL, all communication should be done via message passing. While at first this may hinder usability, once the context gets tainted you need to resort to this anyway, so it doesn't seem like the end result is too different.

**Comment by NAndreasson** [comment]
I agree with your reasoning, like you say the context will most probably get tainted - so it might be best to restrict communication to message passing from the start.

**Comment by deian** [comment]
We're only allowing iframes to be confined for now, so we message passing alone
