### ISSUE TITLE
Potential addition to context tainting algorithm

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#48]
The [context tainting](http://w3c.github.io/webappsec-cowl/#taint-context) algorithm should probably include some step that states that confinement mode should be enabled (if it's currently disabled). This is to ensure that COWL is enabled after inspecting protectedObject attribute on a LabeledObject, this is of course assuming that a LabeledObject can be passed to a context where COWL is not yet enabled.

**Comment by deian** [comment]
Yeah, good point. I was trying to avoid adding that step and instead ensure that invoking the algorithm is only done after enabling COWL, but this is a better approach.
