### ISSUE TITLE
Clarify algorithm for serialization of labels

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#53]
Are the examples below the [label serialization algorithm](http://w3c.github.io/webappsec-cowl/#label-stringifer.), adhering to it? It seems that there should be some edgecase in the algorithm if there is only one dset, to avoid the result being wrapped in "()".  With the current algorithm `a.toString()        === "https://a.com";` would really result in `(https://a.com)`.

**Comment by deian** [comment]
Should also parse without `(`'s https://w3c.github.io/webappsec-cowl/#parse-label-expression
Thanks for pointing this out again!

**Comment by deian** [comment]
Fiex in 50937e1f6b0b406f431b34b3fd150461160db08f
