### ISSUE TITLE
Clarify why both labeled data and labeled context directives are needed

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#55]
With the current specification there are two different types of directives, `data-{confidentiality, integrity}` and `ctx-{confidentiality, integrity, privilege}`. Is there really a need for these two different types of directives? 
# Example

The following header would be used to specify the sensivity of a response (to be used for determining whether to block e.g. requests with the Fetch API and XMLHTTPRequest).
`Sec-COWL: data-confidentiality 'self' AND https://b.com`

The following header is used to specify the initial COWL state of a context. 
`Sec-COWL: ctx-confidentiality 'self'`
# Question

Is there really a need for both of these two different directives? Could we not use something along the lines of `Sec-COWL: confidentiality 'self'; integrity 'self'`for both of the cases above (and set initial state or block response depending on the case)? What would be the drawback? 

+@alejandrorusso

**Comment by deian** [comment]
We need the two for the COWL request header. The UA sends the current context info (`ctx-*`) by default. When sending a labeled object, we need to send the label of the object as well.

For the response header I had originally only had one label ctx- or data-, but this was getting confusing. I still think that having a separation of data vs. ctx is somewhat important. 

Suppose a.com page wants to create an iframe. If the header is:

```
data-confidentiality: a.com
ctx-confidentiality: b.com AND a.com AND c.com
```

The load is allowed and the iframe initial label is `b.com AND a.com AND c.com`.  If we collapse it into one label, this would not be doable.

**Comment by deian** [comment]
Marking as wontfix for now, but happy to chat more.
