### ISSUE TITLE
Missing article or subject verb agreement bug

### ISSUE THREAD

**Issue by lawnsea** [w3c/webappsec-cowl#6]
This sentence is buggy. I can't tell if the issue is a missing article ("a certain category") or subject verb agreement ("certain categories"):

> In some cases it is useful for a particular context to have the privilege to disseminate certain category of data. 
> https://github.com/w3c/webappsec-cowl/blob/master/index.src.html#L483

**Comment by deian** [comment]
@lawnsea thanks for all the PRs!

**Comment by lawnsea** [comment]
@deian my pleasure! i'm really excited to see COWL moving forward.
