### ISSUE TITLE
Extend for Server-Sent Events

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#64]
We might want to extend to specification to handle Server-Sent API. 

A modification would essentially look like what we have for WebSockets right now. 
1. Make sure that we don't leak data by opening a connection to a server. 
2. Make sure that we honor context integrity if set. 

Spec: https://html.spec.whatwg.org/multipage/comms.html#server-sent-events

**Comment by deian** [comment]
disabling this API in cowl iframes
